export const DATA_RECEIVED = 'cart/DATA_RECEIVED';
export const QUANTITY_IN_CART_UPDATED = 'cart/UPDATE_QUANTITY_IN_CART';
export const ADD_ITEM_TO_CART_CLICKED = 'cart/ADD_ITEM_TO_CART';
export const REMOVE_ITEM_FROM_CART_CLICKED = 'cart/REMOVE_ITEM_FROM_CART';
export const REMOVE_ALL_ITEMS_FROM_CART_CLICKED = 'cart/REMOVE_ALL_ITEMS_FROM_CART_CLICKED';
